<?php

namespace JayAnta\ThreatDetection\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class ExportFail2banCommand extends Command
{
    protected $signature = 'threat-detection:export-fail2ban
        {--level= : Filter by threat level (high, medium, low)}
        {--since=24h : Time range (e.g., 1h, 24h, 7d, 30d)}
        {--min-hits=1 : Minimum number of threat entries for an IP}
        {--format=fail2ban : Output format (fail2ban or plain)}
        {--jail=threat-detection : Jail name for fail2ban format}';

    protected $description = 'Export detected threat IPs in fail2ban-compatible format';

    public function handle(): int
    {
        $ips = $this->getBlockableIps();

        if ($ips->isEmpty()) {
            $this->info('No IPs match the given filters.');
            return 0;
        }

        $format = $this->option('format');
        $jail = $this->option('jail');
        $filters = $this->buildFilterDescription();

        if ($format === 'plain') {
            $this->outputPlain($ips, $filters);
        } else {
            $this->outputFail2ban($ips, $filters, $jail);
        }

        return 0;
    }

    private function getBlockableIps()
    {
        $table = config('threat-detection.table_name', 'threat_logs');
        $cutoff = $this->parseSince($this->option('since'));
        $minHits = (int) $this->option('min-hits');
        $level = $this->option('level');

        $query = DB::table($table)
            ->select('ip_address', DB::raw('COUNT(*) as hits'), DB::raw('MAX(created_at) as last_seen'))
            ->where('created_at', '>=', $cutoff)
            ->groupBy('ip_address')
            ->having(DB::raw('COUNT(*)'), '>=', $minHits)
            ->orderByDesc('hits');

        if ($level) {
            $query->where('threat_level', $level);
        }

        return $query->get();
    }

    private function parseSince(string $since): Carbon
    {
        if (preg_match('/^(\d+)h$/i', $since, $m)) {
            return now()->subHours((int) $m[1]);
        }
        if (preg_match('/^(\d+)d$/i', $since, $m)) {
            return now()->subDays((int) $m[1]);
        }
        if (preg_match('/^(\d+)w$/i', $since, $m)) {
            return now()->subWeeks((int) $m[1]);
        }

        return now()->subHours(24);
    }

    private function buildFilterDescription(): string
    {
        $parts = [];
        if ($this->option('level')) {
            $parts[] = 'level=' . $this->option('level');
        }
        $parts[] = 'since=' . $this->option('since');
        $parts[] = 'min-hits=' . $this->option('min-hits');

        return implode(', ', $parts);
    }

    private function outputFail2ban($ips, string $filters, string $jail): void
    {
        $this->line('#!/bin/bash');
        $this->line('# Generated by jayanta/laravel-threat-detection on ' . now()->toDateTimeString());
        $this->line('# Filters: ' . $filters);
        $this->line('# Total IPs: ' . $ips->count());
        $this->line('');

        foreach ($ips as $ip) {
            $this->line("fail2ban-client set {$jail} banip {$ip->ip_address}  # hits: {$ip->hits}, last: {$ip->last_seen}");
        }
    }

    private function outputPlain($ips, string $filters): void
    {
        $this->line('# Generated by jayanta/laravel-threat-detection on ' . now()->toDateTimeString());
        $this->line('# Filters: ' . $filters);
        $this->line('# Total IPs: ' . $ips->count());

        foreach ($ips as $ip) {
            $this->line($ip->ip_address);
        }
    }
}
