<?php

namespace JayAnta\ThreatDetection\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class ExportBlocklistCommand extends Command
{
    protected $signature = 'threat-detection:export-blocklist
        {--level= : Filter by threat level (high, medium, low)}
        {--since=24h : Time range (e.g., 1h, 24h, 7d, 30d)}
        {--min-hits=1 : Minimum number of threat entries for an IP}
        {--format=plain : Output format (plain, csv, nginx, apache)}';

    protected $description = 'Export detected threat IPs as a blocklist in various formats';

    public function handle(): int
    {
        $ips = $this->getBlockableIps();

        if ($ips->isEmpty()) {
            $this->info('No IPs match the given filters.');

            return 0;
        }

        $format = $this->option('format');
        $filters = $this->buildFilterDescription();

        match ($format) {
            'nginx' => $this->outputNginx($ips, $filters),
            'apache' => $this->outputApache($ips, $filters),
            'csv' => $this->outputCsv($ips, $filters),
            default => $this->outputPlain($ips, $filters),
        };

        return 0;
    }

    private function getBlockableIps()
    {
        $table = config('threat-detection.table_name', 'threat_logs');
        $cutoff = $this->parseSince($this->option('since'));
        $minHits = (int) $this->option('min-hits');
        $level = $this->option('level');

        // Rank severity numerically — MAX(threat_level) would be lexicographic
        // ('medium' > 'low' > 'high'), which reports the wrong highest level.
        $levelRank = "MAX(CASE threat_level WHEN 'high' THEN 3 WHEN 'medium' THEN 2 WHEN 'low' THEN 1 ELSE 0 END)";

        $query = DB::table($table)
            ->select('ip_address', DB::raw('COUNT(*) as hits'), DB::raw('MAX(created_at) as last_seen'), DB::raw("{$levelRank} as level_rank"))
            ->where('created_at', '>=', $cutoff)
            ->groupBy('ip_address')
            ->having(DB::raw('COUNT(*)'), '>=', $minHits)
            ->orderByDesc('hits');

        if ($level) {
            $query->where('threat_level', $level);
        }

        return $query->get()->map(function ($row) {
            $row->threat_level = match ((int) $row->level_rank) {
                3 => 'high',
                2 => 'medium',
                1 => 'low',
                default => 'unknown',
            };

            return $row;
        });
    }

    private function parseSince(string $since): Carbon
    {
        if (preg_match('/^(\d+)h$/i', $since, $m)) {
            return now()->subHours((int) $m[1]);
        }
        if (preg_match('/^(\d+)d$/i', $since, $m)) {
            return now()->subDays((int) $m[1]);
        }
        if (preg_match('/^(\d+)w$/i', $since, $m)) {
            return now()->subWeeks((int) $m[1]);
        }

        return now()->subHours(24);
    }

    private function buildFilterDescription(): string
    {
        $parts = [];
        if ($this->option('level')) {
            $parts[] = 'level=' . $this->option('level');
        }
        $parts[] = 'since=' . $this->option('since');
        $parts[] = 'min-hits=' . $this->option('min-hits');

        return implode(', ', $parts);
    }

    private function outputPlain($ips, string $filters): void
    {
        $this->line('# Generated by jayanta/laravel-threat-detection on ' . now()->toDateTimeString());
        $this->line('# Filters: ' . $filters);
        $this->line('# Total IPs: ' . $ips->count());

        foreach ($ips as $ip) {
            $this->line($ip->ip_address);
        }
    }

    private function outputNginx($ips, string $filters): void
    {
        $this->line('# Generated by jayanta/laravel-threat-detection on ' . now()->toDateTimeString());
        $this->line('# Filters: ' . $filters);
        $this->line('# Total IPs: ' . $ips->count());
        $this->line('# Add to nginx server block or include file');

        foreach ($ips as $ip) {
            $this->line("deny {$ip->ip_address};  # hits: {$ip->hits}");
        }
    }

    private function outputApache($ips, string $filters): void
    {
        $this->line('# Generated by jayanta/laravel-threat-detection on ' . now()->toDateTimeString());
        $this->line('# Filters: ' . $filters);
        $this->line('# Total IPs: ' . $ips->count());
        $this->line('# Add to .htaccess or Apache config');

        foreach ($ips as $ip) {
            $this->line("Deny from {$ip->ip_address}  # hits: {$ip->hits}");
        }
    }

    private function outputCsv($ips, string $filters): void
    {
        $this->line('ip_address,hits,last_seen,threat_level');

        foreach ($ips as $ip) {
            $this->line("{$ip->ip_address},{$ip->hits},{$ip->last_seen},{$ip->threat_level}");
        }
    }
}
